### ISSUE TITLE
Place auto complate 

### ISSUE THREAD

**Issue by cappittall** [mlisook/paper-input-place#37] opened 2018-03-18 10:53 UTC
Thank you for the component in advance

I have a web app. And I use this element at two places (home and over the map) both live link below;
- home: https://jobijoy.com/
- map: https://jobijoy.com/maps  (opening with the search button on the map) 

I could not solve yet, On the home page, it is working perfectly, but at map page, it is not working. I tried many ways, but I could not find out. After all, I decided to ask you too.

**Comment by mlisook** [comment] 2018-03-18 13:07
Thank you for submitting this issue!

The problem is with `paper-input-place`.  The code in the `ready()` function incorrectly refers to `google-maps-api` instead of `iron-jsonp-library`.  As a result, if the google maps api is already loaded when the `paper-input-place` is initialized the `_mapsApiLoaded()` function is never called and the autocomplete function is not attached.

On your maps page, the api is already loaded by the `google-map` element.

As the issue is simple to remedy, I'll be pushing an update shortly.

Again, thank you for finding and reporting this important issue.

(By the way, I think your web app is quite attractive)

**Comment by mlisook** [comment] 2018-03-18 13:36
Please update the `paper-input-place` component to 1.9.9 and let me know if this resolution has worked for you.

**Comment by cappittall** [comment] 2018-03-19 05:28
@mlisook, First of all, sorry for my late reply. As I was far from the computer.  I have tested but unfortunately, its the same (I tested on localhost). When it's working, the input letters are black, otherwise red.

**Comment by mlisook** [comment] 2018-03-22 22:42
I apologize for the delay, I've been traveling in an area with little to no internet access.

I've created a page to test with that dynamically adds `paper-input-place` to a page with `google-map` already loaded after waiting 5 seconds to ensure the issue always occurs (which it does).  This exposes a situation in which `paper-input-place` at `_mapsApiLoaded()` line 345 does not attach the `google.maps.places.Autocomplete` function because `this.$.locationsearch.$.nativeInput` is `undefined`.

This in turn is a timing side effect due to recent PRs 608 &  609 on `paper-input` which result in a slight delay before `nativeInput` is set (`paper-input` at `_onIronInputReady()` line 318).

I'm thinking about how best to handle the situation and will report my plans shortly.

**Comment by cappittall** [comment] 2018-03-23 06:17
I saw the info, have a nice trip and Enjoy :) Thank you for your attention also your good comment on the app.

**Comment by cappittall** [comment] 2018-03-27 10:13
I deployed with new version of component in order to see the results.

**Comment by mlisook** [comment] 2018-03-27 12:36
I wonder if I might impose on you to test the latest update for this issue before release.  The attached zip contains an updated `paper-input-place.html` which avoids this issue by removing `paper-input` and implements `paper-input-container` directly instead.  This works in the 6 projects where I use it, and the test I set up for this issue where I'm lazy loading it 5 seconds after loading a map, but I would really appreciate another independent test with your real application.

If you are willing, just substitute this code for the current release you have in `bower_components/paper-input-place` and let me know if it is functioning as you would expect.
[paper-input-place-issue-37-test.zip](https://github.com/mlisook/paper-input-place/files/1851980/paper-input-place-issue-37-test.zip)

**Comment by cappittall** [comment] 2018-03-27 18:31
Yes, this time works very good.

**Comment by roothema** [comment] 2018-03-27 18:57
Hi, I've just started to create an issue due to that I have the same situation when 'this.$.locationsearch.$.nativeInput' is undefined. So I'm right now really happy to see that there will be a new release version with the fix. Also I've tried out the file what you attached and after including it to my project the issue has been disappeared. 👍

**Comment by cappittall** [comment] 2018-03-27 20:44
I just redeployed with new codes. And it's both working perfect. You may check yourself too. 
- home: https://jobijoy.com/
- map: https://jobijoy.com/maps (opening with the search button on the map)

**Comment by mlisook** [comment] 2018-03-27 20:59
I am glad to hear from (both) of you that this change corrects the issue.  I'll be pushing the change with a new version tag today.

**Comment by mlisook** [comment] 2018-03-30 11:33
Thanks for your help with this issue.  I will go ahead and close it now.

**Closed as completed by mlisook** 2018-03-30 11:33 UTC
